# Kubernetes Deployment Configuration for Backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamstring-backend
  labels:
    app: hamstring-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hamstring-backend
  template:
    metadata:
      labels:
        app: hamstring-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/yourusername/hamstring-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        - name: MODEL_PATH
          value: "models/gnode_model.pth"
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sendgrid-api-key
        - name: SENDGRID_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: sendgrid-from-email
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cors-origins
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hamstring-backend
spec:
  selector:
    app: hamstring-backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  sendgrid-from-email: "bulasiokibenge@gmail.com"
  cors-origins: "https://your-frontend-url.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  secret-key: <base64-encoded-secret>
  sendgrid-api-key: <base64-encoded-api-key>
