name: Deploy to Crane Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend Image
      run: |
        cd backend
        docker build -t hamstring-backend:latest .
    
    - name: Deploy to Crane Cloud
      env:
        CRANE_API_KEY: ${{ secrets.CRANE_API_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        echo "Deploying backend to Crane Cloud..."
        # Install Crane CLI
        # curl -sSL https://cranecloud.io/install.sh | bash
        
        # Deploy backend
        # crane deploy \
        #   --app hamstring-backend \
        #   --env SECRET_KEY=${{ secrets.SECRET_KEY }} \
        #   --env SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} \
        #   --env CORS_ORIGINS=${{ secrets.FRONTEND_URL }} \
        #   --dockerfile backend/Dockerfile

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Frontend Image
      run: |
        cd frontend
        docker build \
          --build-arg REACT_APP_API_URL=${{ secrets.BACKEND_URL }} \
          -t hamstring-frontend:latest .
    
    - name: Deploy to Crane Cloud
      env:
        CRANE_API_KEY: ${{ secrets.CRANE_API_KEY }}
      run: |
        echo "Deploying frontend to Crane Cloud..."
        # Deploy frontend
        # crane deploy \
        #   --app hamstring-frontend \
        #   --build-arg REACT_APP_API_URL=${{ secrets.BACKEND_URL }} \
        #   --dockerfile frontend/Dockerfile
    
    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        sleep 30
        # curl -f ${{ secrets.FRONTEND_URL }}
        # curl -f ${{ secrets.BACKEND_URL }}/api/health
